### ISSUE TITLE
defaultOutDir produces invalid path on Windows

### ISSUE THREAD

**Issue by seanssel** [mighdoll/config-file-ts#19]
See related issue in electron-builder: https://github.com/electron-userland/electron-builder/issues/7572

`smushedPath` ends up getting a `:` character from the drive letter portion of the path root: https://github.com/mighdoll/config-file-ts/blob/25600267e7da114c5a12b1e9b30759d7f4b7c16c/src/loadTsConfig.ts#L35

**Comment by mighdoll** [comment]
I haven't been using this library for a while.. would you like to try making a patch? I'd help you for sure!

**Comment by seanssel** [comment]
> I haven't been using this library for a while.. would you like to try making a patch? I'd help you for sure!

Hey, no worries. I'll submit a PR when I have some time to look at this.
