### ISSUE TITLE
config-file-ts 0.2.5 package has no dist folder

### ISSUE THREAD

**Issue by lutzroeder** [mighdoll/config-file-ts#21]
This results in `npx electron-builder` build failures.

```
~: npm install config-file-ts@0.2.5
~: cd node_modules/config-file-ts 
~/node_modules/config-file-ts: ls
LICENSE   README.md package.json  src
```
```
~: npm install config-file-ts@0.2.5
~: cd node_modules/config-file-ts 
~/node_modules/config-file-ts: ls
LICENSE   README.md dist    package.json  src
```

**Comment by bcomnes** [comment]
Seeing this too.

**Comment by hustiez** [comment]
same issue, working fine on windows for some reason

**Comment by ChocolateLoverRaj** [comment]
@hustiez there's no chance it'll work on Windows because it's Windows and not Linux. The different behavior you are finding is probably because of some other reason.

**Comment by hustiez** [comment]
> @hustiez there's no chance it'll work on Windows because it's Windows and not Linux. The different behavior you are finding is probably because of some other reason.

very possible yes. 

Tho after running npm install on linux there is no dist folder and after running it on windows (same project, same commit)

**Comment by bcomnes** [comment]
Rolling back to 0.2.4 with npm overrides provides a dependent fix for now.

**Comment by duan602728596** [comment]
Same error.

**Comment by mighdoll** [comment]
You'd think I'd know better than to publish while on vacation..
LMK if 0.2.6 works for you
