### ISSUE TITLE
Caching not working

### ISSUE THREAD

**Issue by sheam** [mighdoll/config-file-ts#24]
When I load config file, it doesn't seem to be caching the result. 

My codee is like this:

```typescript
const configFile = path.join(process.cwd(), 'test/config.ts');
const cachePath = path.join(process.cwd(), '.mycache');
const config = loadTsConfig<IConfigFile>(configPath, cachePath, true);
```

The config file loads successfully, but the `.mycache` directory is always empty.

I also get the following output every time I run:

```
compiling: [
  'C:\\Users\\supercoder2000\\source\\repos\\project\\src\\config.ts'
]
```

So it seems that the cache is not working?

**Comment by mighdoll** [comment]
can you check to see if 0.2.8-rc1 works for you?

**Comment by sheam** [comment]
Thanks for getting back to me. The 0.2.8-rc1 works, thank you.
